#164563919 Notify Society Secretary whenever Success Ops rejects logged points
AndelaOSP/andela-societies-backend pull request #132
Opened 2019-03-13 10:39 UTC by mutoromike

## Resolves #164563919

## Description

  - Ensures Society Secretaries are notified through Slack, whenever Success Ops users reject logged points, which were previously approved by a Society Secretary.

## Fix

  - Adds a notification functionality which is implemented through Slack Messaging
 
## How to test (describe how to test your PR)

- Clone the repository, install docker, run `make test` within the repository.
- Trigger a build on CircleCI.

## Screenshots
<img width="868" alt="Screenshot 2019-03-13 at 13 38 52" src="https://user-images.githubusercontent.com/26790578/54272781-65b03080-4595-11e9-8eaf-54cb7b582937.png">

2019-03-14 19:30 UTC, frankip approved these changes

2019-03-15 04:55 UTC, georgreen requested changes
Where are the unit tests?

2019-03-15 07:33 UTC, mutoromike commented
@georgreen, the notifications functionalities were refactored to just use one helper file. This was tested to establish whether the `slack-bot` exists or not and whether the API connects to slack or not. Check out this file: `https://github.com/andela/andela-societies-backend/blob/develop/src/tests/test_slack.py`

2019-03-20 11:52 UTC, georgreen approved these changes

2019-03-21 09:03 UTC, merged