#167641775 List All Users
AndelaOSP/andela-societies-backend pull request #142
Opened 2019-08-09 09:26 UTC by mutoromike

## Resolves #167641775

## Description 

  - Get all users and their details fro the API.

## Fix

  - Created a class handling the functionality.
  - Integrated marshmallows for the new requirement

## How to test 

- Clone the repository, install docker, run `make test` within the repository.
- Trigger a build on CircleCI.

## Screenshots

<img width="910" alt="Screenshot 2019-08-09 at 12 07 27" src="https://user-images.githubusercontent.com/26790578/62768983-be321e00-baa0-11e9-89e4-733c3650ba9d.png">

2019-08-16 09:53 UTC, kevinbett approved these changes
Looks good @mutoromike

2019-08-22 07:59 UTC, frankip approved these changes
LGTM

2019-08-22 07:59 UTC, frankip commented on src/tests/test_user_information.py
> +        # super().setUp()
Remove cemented code out

2019-08-25 18:37 UTC, georgreen requested changes
Hey, the logic looks good but I must reject this design as it's not restful(adding an endpoint `user\all`), we already have a user Resource and this would be best implemented there.  

[Here](https://github.com/andela/andela-societies-backend/blob/ffb5989ec07f894939515254c40423cd28e3fb20/src/api/endpoints/users/__init__.py#L13)

I'm interested to know what design choices lead to this particular implementation.

2019-08-26 08:01 UTC, mutoromike commented
@georgreen, thanks for the review. The resource you are referring to, (`UserAPI`), is tailored to return a `single user's data` given the user id. The same resource already has a get method (which implements the functionality). The admin feature needs an endpoint to return a list of users.

We thought it would be a better implementation having a different endpoint returning `all users` since as an `ADMIN`, one would need to view a list of users for them to assign, edit and revoke users roles.

2019-08-26 10:22 UTC, georgreen commented
> @georgreen, thanks for the review. The resource you are referring to, (`UserAPI`), is tailored to return a `single user's data` given the user id. The same resource already has a get method (which implements the functionality). The admin feature needs an endpoint to return a list of users.
> 
> We thought it would be a better implementation having a different endpoint returning `all users` since as an `ADMIN`, one would need to view a list of users for them to assign, edit and revoke users roles.

You can add a `UserAll`  resource with Url `/users/` to this blueprint, check out logged points as an example, it has multiple resources [Here](https://github.com/andela/andela-societies-backend/blob/ffb5989ec0/src/api/endpoints/logged_activities/__init__.py)

2019-08-26 11:00 UTC, mutoromike commented
> > @georgreen, thanks for the review. The resource you are referring to, (`UserAPI`), is tailored to return a `single user's data` given the user id. The same resource already has a get method (which implements the functionality). The admin feature needs an endpoint to return a list of users.
> > We thought it would be a better implementation having a different endpoint returning `all users` since as an `ADMIN`, one would need to view a list of users for them to assign, edit and revoke users roles.
> 
> You can add a `UserAll` resource with Url `/users/` to this blueprint, check out logged points as an example, it has multiple resources [Here](https://github.com/andela/andela-societies-backend/blob/ffb5989ec0/src/api/endpoints/logged_activities/__init__.py)

That's exactly what I've done. There are two resources under this blueprint; `UserAPI` and `UsersAPI`. With `UsersAPI` returning all users when the endpoint `/users/all/` is hit.

2019-10-07 11:32 UTC, merged